### ISSUE TITLE
ReferenceError: WebSocket is not defined

### ISSUE THREAD

**Issue by sparcs360** [enisdenjo/graphql-transport-ws#16]
I've tried running the "Client usage with Apollo" example from the `README.md` under Node.

**Expected Behaviour**
* it works...

**Actual Behaviour**
```
ReferenceError: WebSocket is not defined
    at connect (.../node_modules/graphql-transport-ws/lib/client.js:126:24)
    at .../node_modules/graphql-transport-ws/lib/client.js:220:67
    at Object.createClient (.../node_modules/graphql-transport-ws/lib/client.js:244:11)
    ...
```

**Further Information**
`subscriptions-transport-ws` offers an optional `webSocketImpl` param on the client constructor (https://github.com/apollographql/subscriptions-transport-ws#constructorurl-options-websocketimpl) - any plans to do something similar?

**Comment by enisdenjo** [comment]
Hey @sparcs360, thanks reporting this issue!

Seems like you're trying to use a client in a non-browser environment or the browser is very outdated (doesn't support WebSockets), is this true? I am asking because I want to understand your use-case better.

On the other hand, I've made an issue for supporting custom implementations here: #17.
